LearningManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('selection/', views.subject_selection, name='subject_selection'),
    path('add_assignment/', views.add_assignment, name='add_assignment'),
    path('submit_assignment/<int:assignment_id>/', views.submit_assignment, name='submit_assignment'),
    path('view_submitted_assignments/<int:submitted_assignment_id>', views.view_submitted_assignments, name='view_submitted_assignments'),
]

mainapp/models/assignment.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from mainapp.models import Student


class Assignment(models.Model):
    lecturer = models.ForeignKey(to='Lecturer', on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey(to='Subject', on_delete=models.CASCADE, null=True)
    description = models.TextField(_('Description'))
    deadline_date = models.DateField(_('Deadline date'))
    deadline_time = models.TimeField(_('Deadline time'), null=True)

    def __str__(self):
        return f"{self.subject} - {self.lecturer} - {self.deadline_date} - {self.deadline_time}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        students = Student.objects.filter(lecturers=self.lecturer, subjects=self.subject)
        for student in students:
            student.assignments.add(self)

    class Meta:
        verbose_name = _('Assignment')
        verbose_name_plural = _('Assignments')

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm

from mainapp.models.submitted_assignment import SubmittedAssignment
from mainapp.models.assignment import Assignment
from mainapp.models.subject import Subject


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Email',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()


class SubjectSelectionForm(forms.Form):
    subjects = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(), widget=forms.CheckboxSelectMultiple)


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['subject', 'description', 'deadline_date', 'deadline_time']


class AssignmentSubmissionForm(forms.ModelForm):
    class Meta:
        model = SubmittedAssignment
        fields = ['file']

mainapp/views/login.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main_page')
        else:
            # Return an 'invalid login' error message.
            context = {'invalid_credentials': True}
            return render(request, 'mainapp/login.html', context)
    else:
        return render(request, 'mainapp/login.html')

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone

from .forms import LoginUserForm, AssignmentForm, AssignmentSubmissionForm
from mainapp.models.student import Student
from mainapp.models.subject import Subject
from mainapp.models.assignment import Assignment
from mainapp.models.submitted_assignment import SubmittedAssignment
from .forms import SubjectSelectionForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'mainapp/login.html'
    extra_context = {'title': 'Login'}

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:dashboard')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('faculties'))


@login_required
def dashboard(request):
    user = request.user

    if hasattr(user, 'student'):
        student = user.student
        subjects = student.subjects.all()
        assignments = student.assignments.all()
        return render(request, 'users/dashboard.html', {'student': student,
                                                        'subjects': subjects,
                                                        'assignments': assignments})

    elif hasattr(user, 'lecturer'):
        lecturer = user.lecturer
        assignments = Assignment.objects.filter(lecturer=lecturer)
        submitted_assignments = SubmittedAssignment.objects.filter(lecturer=lecturer)
        return render(request, 'users/dashboard.html', {'lecturer': lecturer,
                                                        'assignments': assignments,
                                                        'submitted_assignments': submitted_assignments})
    else:
        return HttpResponseRedirect(reverse('faculties'))


@login_required
def subject_selection(request):
    user = request.user
    if hasattr(user, 'student'):
        student = user.student
        faculty = student.faculty
    else:
        return HttpResponseRedirect(reverse('faculties'))

    if request.method == 'POST':
        selected_subject_ids = request.POST.getlist('subjects')
        selected_subjects = Subject.objects.filter(id__in=selected_subject_ids, faculty=faculty)
        if len(selected_subjects) > 7:
            error_message = "You can select a maximum of 7 subjects."
            return render(request, 'users/subject_selection.html', {'error_message': error_message})

        student.subjects.clear()
        student.subjects.add(*selected_subjects)
        return HttpResponseRedirect(reverse('users:dashboard'))

    else:
        subjects = faculty.subjects.all()
        return render(request, 'users/subject_selection.html', {'subjects': subjects})


@login_required
def add_assignment(request):
    user = request.user

    if hasattr(user, 'lecturer'):
        if request.method == 'GET':
            form = AssignmentForm()
            return render(request, 'users/add_assignment.html', {'form': form})
        if request.method == 'POST':
            form = AssignmentForm(request.POST)
            if form.is_valid():
                assignment = form.save(commit=False)
                assignment.lecturer = request.user.lecturer
                assignment.save()
                return redirect('users:dashboard')
    else:
        return HttpResponseRedirect(reverse('faculties'))


@login_required
def submit_assignment(request, assignment_id):
    user = request.user

    if hasattr(user, 'student'):
        assignment = Assignment.objects.get(id=assignment_id)
        student = user.student
        lecturer = assignment.lecturer
        if request.method == 'POST':
            form = AssignmentSubmissionForm(request.POST, request.FILES)
            if form.is_valid():
                submission = form.save(commit=False)
                submission.assignment = assignment
                submission.student = student
                submission.lecturer = lecturer
                submission.save()

                student.assignments.remove(assignment)
                return redirect('users:dashboard')
            else:
                print(form.errors)
        else:
            form = AssignmentSubmissionForm()
        return render(request, 'users/submit_assignment.html', {'form': form, 'assignment': assignment})
    else:
        return HttpResponseRedirect(reverse('faculties'))


@login_required
def view_submitted_assignments(request, submitted_assignment_id):
    user = request.user

    if hasattr(user, 'lecturer'):
        assignment = SubmittedAssignment.objects.get(id=submitted_assignment_id)
        return render(request, 'users/submitted_assignment_detail.html', {'assignment': assignment})
    else:
        return HttpResponseRedirect(reverse('faculties'))

users/templates/users/add_assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Assignment</title>
</head>
<body>
{% include 'includes/header.html' %}
    <h1>Add Assignment</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_subject">Subject:</label>
        <select name="subject" id="id_subject">
            {% for choice in form.subject.field.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
        </select><br>

        <label for="id_description">Description:</label>
        <textarea name="description" id="id_description"></textarea><br>

        <label for="id_deadline_date">Deadline Date:</label>
        <input type="date" name="deadline_date" id="id_deadline_date"><br>

        <label for="id_deadline_time">Deadline Time:</label>
        <input type="time" name="deadline_time" id="id_deadline_time"><br>

        <button type="submit">Add Assignment</button>
    </form>
</body>
</html>

users/templates/users/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/detail_pages.css' %}">
</head>
<body>
{% include 'includes/header.html' %}
    <div class="student_info">
        {% if student %}
            <h2>
                {{student.name}} {{student.surname}}<br/>
            </h2>
            <h3>Faculty: {{ student.faculty}}<br/></h3>
            Subjects:
            <ul>
                {% if subjects %}
                    {% for subject in subjects %}
                        <li>{{ subject.title }}</li>
                    {% endfor %}
                {% endif %}
            </ul>
            Assignments:
            <ul>
                {% if assignments %}
                    {% for assignment in assignments %}
                        <li>
                            {{ assignment.subject }}: {{ assignment.description }} - Deadline {{ assignment.deadline_date }}, {{ assignment.deadline_time }}
                            <a href="{% url 'users:submit_assignment' assignment.id %}">
                                <button>Submit</button>
                            </a>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        {% endif %}


        {% if lecturer %}
            <h2>
                {{ lecturer.name }} {{ lecturer.surname }}<br/>
            </h2>
            <h3>
                Your Assignments:<br/>
            </h3>
            <ul>
                {% for assignment in assignments %}
                    <li>
                        {{ assignment.description }} - Deadline: {{ assignment.deadline_date }}, {{ assignment.deadline_time }}
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'users:add_assignment' %}">
                <button>Add assignment</button>
            </a>
            <h3>
                Submitted Assignments:
            </h3>
            <ul>
                {% for submitted_assignment in submitted_assignments %}
                    <li>
                        {{ submitted_assignment.student }} - Submission Date: {{ submitted_assignment.submission_date }}, {{ submitted_assignment.assignment.description }}
                        <a href="{% url 'users:view_submitted_assignments' submitted_assignment.id %}">
                            <button>View</button>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</body>

users/templates/users/login.html
{#!!!!!!!!LOGIN PAGE!!!!#}

{% extends 'mainapp/main_page.html' %}

{% block content %}
<h2 id="log_in">Log in</h2>
    <form method="post" class="login_fields">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Email:</label>
            <input id="username" type="text" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input id="password" type="password" name="password">
        </div>
        <p><button type="submit" id="login_button">Login</button></p>
    </form>

    {% if invalid_credentials %}
        <p>Invalid username or password.</p>
    {% endif %}
{% endblock %}

users/templates/users/subject_selection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subject Selection</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/detail_pages.css' %}">
</head>
<body>
{% include 'includes/header.html' %}

    <h2>Choose Your Subjects</h2>

    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        {% for subject in subjects %}
        <input type="checkbox" id="subject_{{ subject.id }}" name="subjects" value="{{ subject.id }}">
        <label for="subject_{{ subject.id }}">{{ subject.title }}</label><br>
        {% endfor %}

        <button class="choose" type="submit">Submit</button>
    </form>
</body>
</html>

users/templates/users/submit_assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/submitted_assignment_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submit Assignment</title>
</head>
<body>
{% include 'includes/header.html' %}
    {{ assignment.student }}<br/>
    {{ assignment.assignment.description }}<br/>
    <a href="{{ assignment.file.url }}">Download file</a>
</body>
</html>